<a href="https://colab.research.google.com/github/eltondeoliveirasilva/Regressao_Nao_Linear/blob/main/Regressao_Nao_Linear_House.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.datasets import make_moons
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor

In [3]:
house = pd.read_excel('/content/drive/MyDrive/house (1).xlsx')
house.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,192,84,0,0,0,0,0,12,2008,250000

In [4]:
house.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   ExterQual      1460 non-null   object
 10  ExterCond      1460 non-null   object
 11  BsmtFinSF1     1460 non-null   int64
 12  BsmtFinSF2     1460 non-null   int64
 13  BsmtUnfSF      1460 non-null   int64
 14  TotalBsmtSF    1460 non-null   int64
 15  1stFlrSF       1460 non-null   int64
 16  2ndFlrSF       1460 non-null   int64
 17  LowQualFinSF   1460 non-null   int64
 18  GrLivArea      1460 non-null   int64
 19  BsmtFullBath   1460 non-null   int64
 20  BsmtHalfBath   1460 non-null   int64
 21  FullBath       1460 non-null   int64
 22  HalfBath       1460 non-null   int64
 23  BedroomAbvGr   1460 non-null   int64
 24  KitchenAbvGr   1460 non-null   int64
 25  TotRmsAbvGrd   1460 non-null   int64
 26  Fireplaces     1460 non-null   int64
 27  GarageYrBlt    1379 non-null   float64
 28  GarageCars     1460 non-null   int64
 29  GarageArea     1460 non-null   int64
 30  WoodDeckSF     1460 non-null   int64
 31  OpenPorchSF    1460 non-null   int64
 32  EnclosedPorch  1460 non-null   int64
 33  3SsnPorch      1460 non-null   int64
 34  ScreenPorch    1460 non-null   int64
 35  PoolArea       1460 non-null   int64
 36  MiscVal        1460 non-null   int64
 37  MoSold         1460 non-null   int64
 38  YrSold         1460 non-null   int64
 39  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(2)
memory usage: 456.4+ KB

In [6]:
house.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
ExterQual          0
ExterCond          0
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [7]:
house = house.dropna()

In [8]:
house.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
ExterQual        0
ExterCond        0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [9]:
house = pd.get_dummies(house)
house.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,YrSold,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_TA
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,2008,208500,False,False,True,False,False,False,False,True
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,2007,181500,False,False,False,True,False,False,False,True
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,2008,223500,False,False,True,False,False,False,False,True
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,2006,140000,False,False,False,True,False,False,False,True
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,2008,250000,False,False,True,False,False,False,False,True

In [10]:
house.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121 entries, 0 to 1459
Data columns (total 46 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1121 non-null   int64
 1   MSSubClass     1121 non-null   int64
 2   LotFrontage    1121 non-null   float64
 3   LotArea        1121 non-null   int64
 4   OverallQual    1121 non-null   int64
 5   OverallCond    1121 non-null   int64
 6   YearBuilt      1121 non-null   int64
 7   YearRemodAdd   1121 non-null   int64
 8   MasVnrArea     1121 non-null   float64
 9   BsmtFinSF1     1121 non-null   int64
 10  BsmtFinSF2     1121 non-null   int64
 11  BsmtUnfSF      1121 non-null   int64
 12  TotalBsmtSF    1121 non-null   int64
 13  1stFlrSF       1121 non-null   int64
 14  2ndFlrSF       1121 non-null   int64
 15  LowQualFinSF   1121 non-null   int64
 16  GrLivArea      1121 non-null   int64
 17  BsmtFullBath   1121 non-null   int64
 18  BsmtHalfBath   1121 non-null   int64
 19  FullBath       1121 non-null   int64
 20  HalfBath       1121 non-null   int64
 21  BedroomAbvGr   1121 non-null   int64
 22  KitchenAbvGr   1121 non-null   int64
 23  TotRmsAbvGrd   1121 non-null   int64
 24  Fireplaces     1121 non-null   int64
 25  GarageYrBlt    1121 non-null   float64
 26  GarageCars     1121 non-null   int64
 27  GarageArea     1121 non-null   int64
 28  WoodDeckSF     1121 non-null   int64
 29  OpenPorchSF    1121 non-null   int64
 30  EnclosedPorch  1121 non-null   int64
 31  3SsnPorch      1121 non-null   int64
 32  ScreenPorch    1121 non-null   int64
 33  PoolArea       1121 non-null   int64
 34  MiscVal        1121 non-null   int64
 35  MoSold         1121 non-null   int64
 36  YrSold         1121 non-null   int64
 37  SalePrice      1121 non-null   int64
 38  ExterQual_Ex   1121 non-null   bool
 39  ExterQual_Fa   1121 non-null   bool
 40  ExterQual_Gd   1121 non-null   bool
 41  ExterQual_TA   1121 non-null   bool
 42  ExterCond_Ex   1121 non-null   bool
 43  ExterCond_Fa   1121 non-null   bool
 44  ExterCond_Gd   1121 non-null   bool
 45  ExterCond_TA   1121 non-null   bool
dtypes: bool(8), float64(3), int64(35)
memory usage: 350.3 KB

In [11]:
for col in house.select_dtypes(include=['bool']).columns:
    house[col] = house[col].astype(int)

In [12]:
house.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,YrSold,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_TA
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,2008,208500,0,0,1,0,0,0,0,1
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,2007,181500,0,0,0,1,0,0,0,1
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,2008,223500,0,0,1,0,0,0,0,1
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,2006,140000,0,0,0,1,0,0,0,1
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,2008,250000,0,0,1,0,0,0,0,1

In [13]:
labels = np.array(house['SalePrice'])

features = house.drop('SalePrice', axis = 1)

features_list = list(house.columns)

house = np.array(house)

In [14]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [15]:
rf = RandomForestRegressor(n_estimators=1000, random_state=42)
rf.fit(train_features, train_labels);

In [17]:
prediction_rf = rf.predict(test_features)
error_rf = abs(prediction_rf - test_labels)

r_sq = rf.score(features, labels)
print('R^2:',r_sq)
print('MAE:', metrics.mean_absolute_error(test_labels, prediction_rf))
print('MSE:', metrics.mean_squared_error(test_labels, prediction_rf))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, prediction_rf)))

R^2: 0.9485886719577706
MAE: 19122.88696441281
MSE: 937331048.1581936
RMSE: 30615.862688452755

In [18]:
ada = AdaBoostRegressor(n_estimators=1000, random_state=42)
ada.fit(train_features, train_labels);

In [19]:
ada_pred = ada.predict(test_features)

error_ada = abs(ada_pred - test_labels)

In [20]:
r_sq = ada.score(features, labels)
print('R^2:',r_sq)
print('MAE:', metrics.mean_absolute_error(test_labels, ada_pred))
print('MSE:', metrics.mean_squared_error(test_labels, ada_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, ada_pred)))

R^2: 0.868834224815642
MAE: 24702.400413692794
MSE: 1409573730.4590282
RMSE: 37544.29025110247

In [23]:
gbr = GradientBoostingRegressor(n_estimators=1000, random_state=42)
gbr.fit(train_features, train_labels);

In [25]:
gbr_pred = gbr.predict(test_features)

error_gbr = abs(gbr_pred - test_labels)

In [26]:
r_sq = gbr.score(features, labels)
print('R^2:',r_sq)
print('MAE:', metrics.mean_absolute_error(test_labels, gbr_pred))
print('MSE:', metrics.mean_squared_error(test_labels, gbr_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, gbr_pred)))

R^2: 0.9716797837295239
MAE: 17891.3484186379
MSE: 768539758.2485199
RMSE: 27722.54963470207